### ISSUE TITLE
Dataset configuration not clearly defined

### ISSUE THREAD

**Issue by govind17** [sjj0403/GSCS#2]
Hi, 

In Hu dataset, Java contains code.original, code.original_subtoken and javadoc.original but the config files has asked for train_code_path, train_type_path and train_nl_path. How do you relate them?

Thanks.

**Comment by sjj0403** [comment]
The train_code_path corresponds to&nbsp;code.original, train_type_path corresponds to code.original_subtoken and train_nl_path corresponds to javadoc.original.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, May 22, 2022 06:15 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[sjj0403/GSCS] Dataset configuration not clearly defined (Issue #2)

&nbsp;



 
Hi,
 
In Hu dataset, Java contains code.original, code.original_subtoken and javadoc.original but the config files has asked for train_code_path, train_type_path and train_nl_path. How do you relate them?
 
Thanks.

**Comment by govind17** [comment]
Can we use the java_with_sbt dataset the same way? 
train_code_path = code.sbt
train_type_path = code.sbt_tag
and train_nl_path = javadoc.original/ javadoc.first_sent

Thank-you for your response

**Comment by sjj0403** [comment]
The train_code_path corresponds to&nbsp;code.original_subtoken, train_type_path corresponds to node sequence (which can be obtained by the function&nbsp;get_adjacent2 in file&nbsp;strudata.py) and train_nl_path corresponds to javadoc.original. Edge file (which can be obtained by the function&nbsp;get_adjacent in file&nbsp;strudata.py) is also used in our approach. But as it is too big, you can split it into several small files.
&nbsp;
&nbsp;
------------------ Original ------------------
From: &nbsp;"Govind ***@***.***&gt;;
Date: &nbsp;Sun, May 22, 2022 06:15 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[sjj0403/GSCS] Dataset configuration not clearly defined (Issue #2)

&nbsp;



 
Hi,
 
In Hu dataset, Java contains code.original, code.original_subtoken and javadoc.original but the config files has asked for train_code_path, train_type_path and train_nl_path. How do you relate them?
 
Thanks.

**Comment by govind17** [comment]
Thank-you
